# Tmux configuration

# Set colors
set -g default-terminal "tmux-256color"

# List of plugins
set -g @rose_pine_variant 'main'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager
run '~/.config/tmux/plugins/tpm/tpm'
