# Tmux configuration

# List of plugins
set -g @rose_pine_variant 'main'
set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tpm'

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
