# Alacritty configuration

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.95

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 24

[keyboard]
bindings = [
    { key = "Return", mods = "Shift", chars = "\n" }
]

[general]
#import = ["~/.config/alacritty/tokyonight_storm-folke.toml"]
import = ["~/.config/alacritty/tokyonight_storm-zatchheems.toml"]
