# Alacritty configuration

[general]
import = ["rose-pine.toml"]

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 1
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 24

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "Return", mods = "Shift", chars = "\n" }
]
